"""empty message

Revision ID: 2905d77e1be0
Revises: 30ccc4e50d6c
Create Date: 2024-09-13 12:27:57.738166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2905d77e1be0'
down_revision = '30ccc4e50d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('homeplanet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planets', ['homeplanet_id'], ['id'])
        batch_op.create_foreign_key(None, 'gender', ['gender_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('system', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('inhabitants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capital_city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorite_planets_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_favorite_characters_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_planets')
        batch_op.drop_column('favorite_characters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_characters', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_planets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_favorite_characters_fkey', 'characters', ['favorite_characters'], ['id'])
        batch_op.create_foreign_key('user_favorite_planets_fkey', 'planets', ['favorite_planets'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('coordinates')
        batch_op.drop_column('capital_city')
        batch_op.drop_column('inhabitants')
        batch_op.drop_column('system')
        batch_op.drop_column('sector')
        batch_op.drop_column('region')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gender_id')
        batch_op.drop_column('homeplanet_id')
        batch_op.drop_column('species')

    op.drop_table('favorites')
    op.drop_table('gender')
    # ### end Alembic commands ###
