"""empty message

Revision ID: 30ccc4e50d6c
Revises: 8dedb874e953
Create Date: 2024-09-11 21:20:28.847412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ccc4e50d6c'
down_revision = '8dedb874e953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_characters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_planets', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'characters', ['favorite_characters'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['favorite_planets'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_planets')
        batch_op.drop_column('favorite_characters')

    # ### end Alembic commands ###
