"""empty message

Revision ID: 607825ec0080
Revises: a5cffa318ac2
Create Date: 2024-09-11 18:46:16.210315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607825ec0080'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('creation_date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
