"""empty message

Revision ID: 9999d9092a42
Revises: 2905d77e1be0
Create Date: 2024-09-13 12:33:29.157984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9999d9092a42'
down_revision = '2905d77e1be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('characters_gender_id_fkey', type_='foreignkey')
        batch_op.drop_column('gender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('characters_gender_id_fkey', 'gender', ['gender_id'], ['id'])
        batch_op.drop_column('gender')

    op.create_table('gender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gender_pkey')
    )
    # ### end Alembic commands ###
